name: sprint
version: 1.0.0+1
description: Fully-documented, simple and complete message-printing library
author: Dorian Oszczęda <vxern@wordcollector.co.uk>
homepage: https://github.com/vxern/sprint
repository: https://github.com/vxern/sprint
#documentation:
issue_tracker: https://github.com/vxern/sprint/issues

publish_to: https://pub.dev

environment:
  sdk: '>=2.13.3 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  
dependencies: 
  ansicolor: ^2.0.1
